#!/usr/bin/env tsx

import fs from "fs/promises";
import path from "path";
import { createClient } from "@supabase/supabase-js";

/**
 * User Migration Script
 *
 * Migrates users from Supabase Auth to new authentication system.
 * Generates SQL for inserting users into Prisma database.
 *
 * Usage:
 *   tsx migration/scripts/migrate-users.ts \
 *     --from ../project-name-lovable \
 *     --to ./prisma/schema.prisma
 *
 * Requires:
 *   - SUPABASE_URL environment variable
 *   - SUPABASE_SERVICE_ROLE_KEY environment variable
 */

interface SupabaseUser {
  id: string;
  email: string;
  created_at: string;
}

interface Profile {
  id: string;
  nombre: string | null;
  apellidos: string | null;
  unidad: string | null;
}

interface UserRole {
  user_id: string;
  role: string;
}

interface MigrationOptions {
  lovableProjectPath: string;
  outputPath: string;
  supabaseUrl: string;
  supabaseServiceKey: string;
}

async function loadSupabaseTypes(projectPath: string): Promise<string> {
  const typesPath = path.join(
    projectPath,
    "src/integrations/supabase/types.ts",
  );

  try {
    return await fs.readFile(typesPath, "utf-8");
  } catch (error) {
    throw new Error(
      `Could not read Supabase types from ${typesPath}: ${error instanceof Error ? error.message : "Unknown error"}`,
    );
  }
}

function detectTables(typesContent: string): string[] {
  const tablePattern = /(\w+):\s*\{\s*Row:/g;
  const tables: string[] = [];

  let match: RegExpExecArray | null;
  while ((match = tablePattern.exec(typesContent)) !== null) {
    tables.push(match[1]);
  }

  return tables;
}

async function fetchSupabaseUsers(
  supabase: ReturnType<typeof createClient>,
): Promise<SupabaseUser[]> {
  console.log("📥 Fetching users from Supabase Auth...");

  const { data, error } = await supabase.auth.admin.listUsers();

  if (error) {
    throw new Error(`Failed to fetch users: ${error.message}`);
  }

  console.log(`   Found ${data.users.length} users`);
  return data.users.map((user) => ({
    id: user.id,
    email: user.email!,
    created_at: user.created_at,
  }));
}

async function fetchProfiles(
  supabase: ReturnType<typeof createClient>,
): Promise<Map<string, Profile>> {
  console.log("📥 Fetching user profiles...");

  const { data, error } = await supabase.from("profiles").select("*");

  if (error) {
    console.warn(`   Warning: Could not fetch profiles: ${error.message}`);
    return new Map();
  }

  const profiles = new Map<string, Profile>();
  for (const profile of data || []) {
    profiles.set(profile.id, {
      id: profile.id,
      nombre: profile.nombre,
      apellidos: profile.apellidos,
      unidad: profile.unidad,
    });
  }

  console.log(`   Found ${profiles.size} profiles`);
  return profiles;
}

async function fetchUserRoles(
  supabase: ReturnType<typeof createClient>,
): Promise<Map<string, string[]>> {
  console.log("📥 Fetching user roles...");

  const { data, error } = await supabase.from("user_roles").select("*");

  if (error) {
    console.warn(`   Warning: Could not fetch roles: ${error.message}`);
    return new Map();
  }

  const userRoles = new Map<string, string[]>();
  for (const userRole of data || []) {
    const roles = userRoles.get(userRole.user_id) || [];
    roles.push(userRole.role);
    userRoles.set(userRole.user_id, roles);
  }

  console.log(`   Found roles for ${userRoles.size} users`);
  return userRoles;
}

function generateSQL(
  users: SupabaseUser[],
  profiles: Map<string, Profile>,
  userRoles: Map<string, string[]>,
): string {
  const lines: string[] = [];

  lines.push("-- User Migration SQL");
  lines.push("-- Generated by migrate-users.ts");
  lines.push(`-- Date: ${new Date().toISOString()}`);
  lines.push("-- Users will need to reset their passwords");
  lines.push("");

  lines.push("BEGIN;");
  lines.push("");

  lines.push("-- Insert users");
  for (const user of users) {
    const profile = profiles.get(user.id);

    const nombre = profile?.nombre
      ? `'${profile.nombre.replace(/'/g, "''")}'`
      : "NULL";
    const apellidos = profile?.apellidos
      ? `'${profile.apellidos.replace(/'/g, "''")}'`
      : "NULL";
    const unidad = profile?.unidad
      ? `'${profile.unidad.replace(/'/g, "''")}'`
      : "NULL";

    lines.push(
      `INSERT INTO "User" ("id", "email", "passwordHash", "nombre", "apellidos", "unidad", "isActive", "createdAt")`,
    );
    lines.push(`VALUES (`);
    lines.push(`  '${user.id}',`);
    lines.push(`  '${user.email}',`);
    lines.push(`  '',  -- Empty password hash, user must reset`);
    lines.push(`  ${nombre},`);
    lines.push(`  ${apellidos},`);
    lines.push(`  ${unidad},`);
    lines.push(`  true,`);
    lines.push(`  '${user.created_at}'`);
    lines.push(`);`);
    lines.push("");
  }

  lines.push("-- Insert user roles");
  for (const [userId, roles] of userRoles.entries()) {
    for (const role of roles) {
      lines.push(`INSERT INTO "UserRole" ("userId", "roleId")`);
      lines.push(`VALUES ('${userId}', '${role}');`);
      lines.push("");
    }
  }

  lines.push("COMMIT;");
  lines.push("");

  lines.push("-- Send password reset emails");
  lines.push("-- Run this separately after users are imported:");
  lines.push('-- SELECT email FROM "User" WHERE "passwordHash" = \'\';');

  return lines.join("\n");
}

async function generatePasswordResetList(
  users: SupabaseUser[],
  outputDir: string,
): Promise<void> {
  const emails = users.map((user) => user.email);
  const content = emails.join("\n") + "\n";

  const filePath = path.join(outputDir, "users-need-password-reset.txt");
  await fs.writeFile(filePath, content, "utf-8");

  console.log(`\n📧 Password reset list: ${filePath}`);
  console.log("   Send password reset emails to these users");
}

async function migrateUsers(options: MigrationOptions): Promise<void> {
  console.log("👥 Supabase User Migration");
  console.log("===========================\n");

  const supabase = createClient(
    options.supabaseUrl,
    options.supabaseServiceKey,
    {
      auth: {
        autoRefreshToken: false,
        persistSession: false,
      },
    },
  );

  const typesContent = await loadSupabaseTypes(options.lovableProjectPath);
  const tables = detectTables(typesContent);

  if (!tables.includes("profiles")) {
    console.warn('⚠️  Warning: "profiles" table not found in types.ts');
  }

  if (!tables.includes("user_roles")) {
    console.warn('⚠️  Warning: "user_roles" table not found in types.ts');
  }

  const users = await fetchSupabaseUsers(supabase);
  const profiles = await fetchProfiles(supabase);
  const userRoles = await fetchUserRoles(supabase);

  if (users.length === 0) {
    console.log("⚠️  No users found. Nothing to migrate.");
    return;
  }

  console.log("\n📝 Generating SQL...");
  const sql = generateSQL(users, profiles, userRoles);

  const outputDir = path.dirname(options.outputPath);
  await fs.mkdir(outputDir, { recursive: true });

  await fs.writeFile(options.outputPath, sql, "utf-8");
  console.log(`✅ SQL generated: ${options.outputPath}`);

  await generatePasswordResetList(users, outputDir);

  console.log("\n✨ Migration SQL ready!");
  console.log("\n📋 Next steps:");
  console.log("   1. Review the generated SQL:");
  console.log(`      cat ${options.outputPath}`);
  console.log("   2. Apply to database:");
  console.log(`      psql $DATABASE_URL -f ${options.outputPath}`);
  console.log("   3. Send password reset emails to users:");
  console.log(
    `      cat ${path.join(outputDir, "users-need-password-reset.txt")}`,
  );
  console.log("   4. Configure email service for password resets");
  console.log(
    "\n⚠️  IMPORTANT: Users cannot login until they reset their passwords!",
  );
}

async function main(): Promise<void> {
  const args = process.argv.slice(2);

  let lovableProjectPath = "";
  let outputPath = "migration/output/user-migration.sql";

  for (let i = 0; i < args.length; i++) {
    if (args[i] === "--from" && args[i + 1]) {
      lovableProjectPath = args[i + 1];
      i++;
    } else if (args[i] === "--to" && args[i + 1]) {
      outputPath = args[i + 1].replace("schema.prisma", "user-migration.sql");
      i++;
    }
  }

  if (!lovableProjectPath) {
    console.error("❌ Error: --from parameter required");
    console.error("   Usage: tsx migrate-users.ts --from ../lovable-project");
    process.exit(1);
  }

  const supabaseUrl = process.env.SUPABASE_URL;
  const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!supabaseUrl || !supabaseServiceKey) {
    console.error("❌ Error: Supabase credentials not found");
    console.error("   Set environment variables:");
    console.error("   - SUPABASE_URL");
    console.error("   - SUPABASE_SERVICE_ROLE_KEY");
    process.exit(1);
  }

  try {
    await migrateUsers({
      lovableProjectPath,
      outputPath,
      supabaseUrl,
      supabaseServiceKey,
    });
  } catch (error) {
    console.error("\n❌ Migration failed:");
    console.error(error instanceof Error ? error.message : "Unknown error");
    if (error instanceof Error && error.stack) {
      console.error("\nStack trace:");
      console.error(error.stack);
    }
    process.exit(1);
  }
}

main();
