name: boilerplate-api

services:
  redis:
    image: redis:7.4-alpine
    ports:
      - 35302:6379
    volumes:
      - ./redis/volumes/data:/data
    restart: unless-stopped
    networks:
      - net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  mongo:
    image: mongo:8
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: boilerplate-api
    ports:
      - 26943:27017
    volumes:
      - ./mongo/volumes/data:/data/db
    restart: unless-stopped
    networks:
      - net
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: boilerplate-api
    ports:
      - "54320:5432"
    volumes:
      - ./postgres/volumes/data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  dbgate:
    image: dbgate/dbgate
    restart: unless-stopped
    environment:
      CONNECTIONS: con1,con2,con3
      LABEL_con1: Postgres
      SERVER_con1: postgres
      USER_con1: postgres
      PASSWORD_con1: postgres
      PORT_con1: 5432
      ENGINE_con1: postgres@dbgate-plugin-postgres

      LABEL_con2: MongoDB
      SERVER_con2: mongo
      USER_con2: mongo
      PASSWORD_con2: mongo
      PORT_con2: 27017
      ENGINE_con2: mongo@dbgate-plugin-mongo

      LABEL_con3: Redis
      SERVER_con3: redis
      PORT_con3: 6379
      ENGINE_con3: redis@dbgate-plugin-redis

    volumes:
      - dbgate-data:/root/.dbgate
    ports:
      - "55401:3000"
    depends_on:
      - postgres
      - mongo
      - redis
    networks:
      - net
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 15s

  mailpit:
    image: "axllent/mailpit:latest"
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: unless-stopped
    networks:
      - net
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8025"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  dbgate-data:

networks:
  net:
    driver: bridge
