/**
 * AI Route Generator - AI-Assisted Script
 * Generates Fastify CRUD routes from Prisma schema using Claude/Gemini
 */

import * as fs from "fs";
import * as path from "path";
import { BaseMigrator, type MigrationAIConfig } from "./base-migrator.js";

export interface RouteGenerationOptions {
  schemaPath?: string;
  outputDir?: string;
  includeAuth?: boolean;
  includeValidation?: boolean;
  includeSwagger?: boolean;
}

export class RouteGenerator extends BaseMigrator {
  constructor(config: MigrationAIConfig) {
    super(config);
  }

  async generateRoutes(options: RouteGenerationOptions = {}): Promise<void> {
    const {
      schemaPath = "prisma/schema.prisma",
      outputDir = "src/routes/generated",
      includeAuth = true,
      includeValidation = true,
      includeSwagger = true,
    } = options;

    console.log("📖 Reading Prisma schema...");
    if (!fs.existsSync(schemaPath)) {
      throw new Error(`Schema not found: ${schemaPath}`);
    }

    const schemaContent = fs.readFileSync(schemaPath, "utf-8");

    // Extract models from schema
    const models = this.extractModels(schemaContent);
    console.log(`📝 Found ${models.length} models: ${models.join(", ")}`);

    const systemPrompt = this.buildRoutePrompt(
      includeAuth,
      includeValidation,
      includeSwagger,
    );

    for (const model of models) {
      console.log(`🤖 Generating routes for ${model}...`);

      const userPrompt = `Generate CRUD routes for model: ${model}

Prisma Schema:
\`\`\`prisma
${this.extractModelDefinition(schemaContent, model)}
\`\`\`

Requirements:
- Fastify plugin with TypeScript
- CRUD operations: GET (list), GET /:id, POST, PUT /:id, DELETE /:id
- Pagination for list (page, limit)
- Error handling (404, 400, 500)
${includeAuth ? "- Authentication required (authAccessToken plugin)" : ""}
${includeValidation ? "- AJV schema validation" : ""}
${includeSwagger ? "- Swagger/OpenAPI decorators" : ""}
`;

      const routeCode = await super.generate(systemPrompt, userPrompt);
      let cleanedCode = super.cleanMarkdownWrapper(routeCode);

      // Post-process: Remove any text after "export default routes;"
      cleanedCode = this.cleanGeneratedCode(cleanedCode);

      // Save to file
      const routeFileName = this.modelToRouteName(model);
      const routePath = path.join(outputDir, routeFileName);

      if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
      }

      fs.writeFileSync(routePath, cleanedCode, "utf-8");
      console.log(`✅ Generated: ${routePath}`);
    }

    console.log("\n✅ Route generation complete!");
    console.log(`📁 Routes saved to: ${outputDir}`);

    // Generate index.ts to auto-register all routes
    this.generateRoutesIndex(outputDir, models);

    // Auto-register generated routes in private/index.ts
    this.registerInPrivateRoutes();

    // Update test scripts with generated endpoint names
    this.updateTestScripts(models);
  }

  /**
   * Clean generated code by removing explanatory text after export statement
   */
  private cleanGeneratedCode(code: string): string {
    // Find last occurrence of "export default"
    const exportMatch = code.lastIndexOf("export default");
    if (exportMatch === -1) return code;

    // Find the semicolon after export default
    const semicolonAfterExport = code.indexOf(";", exportMatch);
    if (semicolonAfterExport === -1) return code;

    // Return code up to and including that semicolon
    return code.substring(0, semicolonAfterExport + 1).trim();
  }

  /**
   * Generate index.ts file to auto-register all generated routes
   */
  private generateRoutesIndex(outputDir: string, models: string[]): void {
    console.log("\n📝 Generating routes index...");

    const imports = models
      .map((model) => {
        const varName = `${model.toLowerCase()}Routes`;
        const fileName = this.modelToRouteName(model).replace(".ts", ".js");
        return `import ${varName} from "./${fileName}";`;
      })
      .join("\n");

    const registrations = models
      .map((model) => {
        const varName = `${model.toLowerCase()}Routes`;
        const prefix = `/${this.modelToKebabCase(model)}`;
        return `  fastify.register(${varName}, { prefix: "${prefix}" });`;
      })
      .join("\n");

    const indexContent = `// ⚠️ AUTO-GENERATED FILE - Do not edit manually
// Generated by route-generator.ts
import type { FastifyInstance } from "fastify";

${imports}

export default async (fastify: FastifyInstance): Promise<void> => {
${registrations}
};
`;

    const indexPath = path.join(outputDir, "index.ts");
    fs.writeFileSync(indexPath, indexContent, "utf-8");
    console.log(`✅ Generated: ${indexPath}`);
  }

  /**
   * Auto-register generated routes in src/routes/private/index.ts
   */
  private registerInPrivateRoutes(): void {
    console.log("\n📝 Registering generated routes in private/index.ts...");

    const privateIndexPath = path.join(
      process.cwd(),
      "src",
      "routes",
      "private",
      "index.ts",
    );

    if (!fs.existsSync(privateIndexPath)) {
      console.log("⚠️  private/index.ts not found, skipping auto-registration");
      return;
    }

    let content = fs.readFileSync(privateIndexPath, "utf-8");

    // Check if already registered
    if (content.includes('from "../generated/index.js"')) {
      console.log("✅ Generated routes already registered in private/index.ts");
      return;
    }

    // Find the last import statement
    const lines = content.split("\n");
    let lastImportIndex = -1;

    for (let i = 0; i < lines.length; i++) {
      if (
        lines[i].trim().startsWith("import ") &&
        !lines[i].includes("type {")
      ) {
        lastImportIndex = i;
      }
    }

    // Insert the import after the last import
    if (lastImportIndex !== -1) {
      lines.splice(
        lastImportIndex + 1,
        0,
        'import generatedRoutes from "../generated/index.js";',
      );
    }

    // Find the export default function and add registration
    const exportIndex = lines.findIndex((line) =>
      line.includes("export default async"),
    );
    if (exportIndex !== -1) {
      // Find the last fastify.register call
      let lastRegisterIndex = -1;
      for (let i = exportIndex; i < lines.length; i++) {
        if (lines[i].includes("fastify.register(")) {
          lastRegisterIndex = i;
        }
      }

      if (lastRegisterIndex !== -1) {
        // Add after last register, with empty line and comment
        lines.splice(
          lastRegisterIndex + 1,
          0,
          "",
          "  // Auto-generated CRUD routes",
          "  fastify.register(generatedRoutes);",
        );
      }
    }

    content = lines.join("\n");
    fs.writeFileSync(privateIndexPath, content, "utf-8");
    console.log("✅ Registered generated routes in private/index.ts");
  }

  /**
   * Update test scripts with generated endpoint names
   */
  private updateTestScripts(models: string[]): void {
    console.log("\n📝 Updating test scripts with endpoint names...");

    const endpointNames = models.map((model) => this.modelToKebabCase(model));
    const endpointsArrayString = `const ENDPOINTS_TO_TEST: string[] = [\n  ${endpointNames.map((e) => `"${e}"`).join(",\n  ")},\n];`;

    // Update test-migration.ts
    const testMigrationPath = path.join(process.cwd(), "test-migration.ts");
    if (fs.existsSync(testMigrationPath)) {
      let content = fs.readFileSync(testMigrationPath, "utf-8");
      content = content.replace(
        /const ENDPOINTS_TO_TEST: string\[\] = \[[\s\S]*?\];/,
        endpointsArrayString,
      );
      fs.writeFileSync(testMigrationPath, content, "utf-8");
      console.log(
        "✅ Updated test-migration.ts with " + models.length + " endpoints",
      );
    }

    // Update quick-test.ts
    const quickTestPath = path.join(process.cwd(), "quick-test.ts");
    if (fs.existsSync(quickTestPath)) {
      let content = fs.readFileSync(quickTestPath, "utf-8");
      content = content.replace(
        /const ENDPOINTS_TO_TEST: string\[\] = \[[\s\S]*?\];/,
        endpointsArrayString,
      );
      fs.writeFileSync(quickTestPath, content, "utf-8");
      console.log(
        "✅ Updated quick-test.ts with " + models.length + " endpoints",
      );
    }
  }

  private modelToKebabCase(modelName: string): string {
    // ExpedienteEntity -> expediente-entity
    // Profile -> profile
    return modelName
      .replace(/([a-z])([A-Z])/g, "$1-$2")
      .toLowerCase()
      .replace(/entity$/, "")
      .replace(/-$/, "");
  }

  private extractModels(schema: string): string[] {
    const modelRegex = /^model (\w+)/gm;
    const models: string[] = [];
    let match;

    while ((match = modelRegex.exec(schema)) !== null) {
      if (match[1]) {
        models.push(match[1]);
      }
    }

    return models;
  }

  private extractModelDefinition(schema: string, modelName: string): string {
    const modelRegex = new RegExp(`model ${modelName} \\{[^}]+\\}`, "s");
    const match = schema.match(modelRegex);
    return match ? match[0] : "";
  }

  private modelToRouteName(modelName: string): string {
    // ExpedienteEntity -> expediente.routes.ts
    const baseName = modelName.replace(/Entity$/, "");
    return `${baseName.toLowerCase()}.routes.ts`;
  }

  private buildRoutePrompt(
    includeAuth: boolean,
    includeValidation: boolean,
    includeSwagger: boolean,
  ): string {
    return `You are an expert backend developer specializing in Fastify + Prisma + TypeScript.

Generate production-ready CRUD routes following these patterns:

**File Structure:**
\`\`\`typescript
import type { FastifyPluginAsync } from 'fastify';
import type { PrismaClient } from '@prisma/client';

const routes: FastifyPluginAsync = async (fastify) => {
  const prisma: PrismaClient = fastify.prisma;

  // Routes here
};

export default routes;
\`\`\`

**Patterns to follow:**
1. Use Fastify's async/await error handling
2. Return proper HTTP status codes (200, 201, 404, 400, 500)
3. Pagination: \`{ page: 1, limit: 10 }\` → \`{ data: [], total, page, limit, totalPages }\`
4. ID validation: Check if entity exists before update/delete${includeAuth ? "\n5. Auth: Use \`{ preValidation: [fastify.authAccessToken] }\`" : ""}${includeValidation ? "\n6. Validation: AJV schemas in route options" : ""}${includeSwagger ? "\n7. Swagger: Add schema: { tags, description, response, body }" : ""}

**Error handling example:**
\`\`\`typescript
const entity = await prisma.model.findUnique({ where: { id } });
if (!entity) {
  return reply.status(404).send({ error: 'Entity not found' });
}
\`\`\`

**CRITICAL REQUIREMENTS:**
- Output ONLY valid TypeScript code
- NO explanatory text after the code
- NO markdown formatting outside of code blocks  
- The file MUST end with "export default routes;" 
- DO NOT include sentences like "This implementation provides..." or any text after the export statement

Generate complete, production-ready code with NO placeholders or "... existing code ..." comments.`;
  }
}

// CLI execution - Immediate IIFE for ESM compatibility
(async () => {
  // Check if this is the main module
  const isMainModule =
    process.argv[1] &&
    import.meta.url.endsWith(process.argv[1].replace(/\\/g, "/"));

  if (!isMainModule) return;

  try {
    const config = BaseMigrator.loadConfig();
    const generator = new RouteGenerator(config);

    const args = process.argv.slice(2);
    const options: RouteGenerationOptions = {
      includeAuth: !args.includes("--no-auth"),
      includeValidation: !args.includes("--no-validation"),
      includeSwagger: !args.includes("--no-swagger"),
    };

    await generator.generateRoutes(options);
  } catch (error) {
    console.error(
      "❌ Route generation error:",
      error instanceof Error ? error.message : String(error),
    );
    process.exit(1);
  }
})();
